#ifndef	SMARC_QUAD_REV_SA01_CONFIG
#define	SMARC_QUAD_REV_SA01_CONFIG
#include "mx6_rev-sa01.h"

#define CONFIG_MX6Q
#define CONFIG_MX6Q_SMARC
#define	MEMORY_2G_SMARC

#define	CONFIG_SYS_PROMPT	"MX6 QUAD SMARC U-Boot > "
#define	PHYS_SDRAM_1_SIZE	(2u * 1024 * 1024 * 1024)
#endif
